### PR TITLE
♻️refactor: simplify and minimum

### PR DESCRIPTION
**Pull request by Marukome0743**
# Sammary

- [x]  Fix netlify Deploy Preview
- [x] use jsx.element instead of FC
- [x] decrease some useless fields and properties
- [x] implement unique id by react.useId
- [x] Change image preview function more simple
- [x] Rename undenstandably

## How to verify the codes
I tested the codes in my environment.
I haven't make any tests, but I would like in the future.
Anyway check the my changes at the netlify deploy preview.

### CODE REVIEW

**Review by tanePON — APPROVED** [review]

**Review by kazutan1230 — COMMENTED** [review]
Please tell me why you changed
- uoloadFormHook.tsx to profileForm.tsx
- type FormData to Profile
?

**Comment by Marukome0743** [comment]
> Please tell me why you changed
> 
> * uoloadFormHook.tsx to profileForm.tsx
> * type FormData to Profile
>   ?

I wanna try [DDD](https://ja.wikipedia.org/wiki/%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E9%A7%86%E5%8B%95%E8%A8%AD%E8%A8%88)(Domain-Driven Design).
This software design focus on the name of business domain.

DDD big benefit is **more readable codes for whoever**.
[This book](https://nikkie-ftnext.hatenablog.com/entry/itbookaward-2023-1-minodriven-book) will help you understand .

**Comment by kazutan1230** [comment]
> I wanna try [DDD](https://ja.wikipedia.org/wiki/%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E9%A7%86%E5%8B%95%E8%A8%AD%E8%A8%88)(Domain-Driven Design). This software design focus on the name of business domain.
I read the overview of DDD.
I think labor management is a business domain of this application,
how about you?

Then, I wonder whether the name, "_Profile_", is correct here because of below.
- In the form, there are "**agreement**" and "**image**"(disability certificate image) which we are difficult to call "_Profile_".
- Regardless of the business dmain, this type and form are just related to form's data.
- In the future, it is expected to register information for "**内勤担当者**" in this application.

> DDD big benefit is **more readable codes for whoever**. [This book](https://nikkie-ftnext.hatenablog.com/entry/itbookaward-2023-1-minodriven-book) will help you understand .

I'll read the book.

**Review by kazutan1230 — APPROVED** [review]
I approve PR.

**Pull request merged**
